export const searchCouponWithNoCoupon = {
  label: "Apply",
  disableManualType: false,
  placeholder: "Enter Coupon Code",
  couponCode: ""
};

export const productCouponDetailsOldResponse = {
  closeModal: () => {},
  applyUserCoupon: () => {},
  releaseUserCoupon: () => {},
  type: "mplFinalVisibleCouponsDTO",
  status: "Success",
  opencouponsList: [
    {
      couponCode: "AXIS5_Coupon",
      couponCreationDate: "Mon May 11 06:06:06 IST 2020",
      couponExpiryDate: "Sun Apr 11 06:06:06 IST 2021",
      couponName: "AXIS5_Coupon",
      couponSequenceNumber: 999,
      couponType: "COUPON",
      isPercentage: true,
      marketIndicator: "marketplace",
      maxDiscount: 500,
      value: 5
    },
    '{couponCode: "DCNCE3APPLY", couponCreationDate: "Su…}',
    '{couponCode: "Couponone", couponCreationDate: "Sat …}'
  ],
  match: {
    path: "/cart",
    url: "/cart",
    isExact: true,
    params: "{}"
  },
  location: {
    pathname: "/cart",
    search: "",
    hash: "",
    key: "7wlr5w"
  },
  history: {
    length: 8,
    action: "POP",
    location: '{hash: "", key: "7wlr5w", pathname: "/cart", search…}',
    createHref: "ƒ createHref() {}",
    push: "ƒ push() {}",
    replace: "ƒ replace() {}",
    go: "ƒ go() {}",
    goBack: "ƒ goBack() {}",
    goForward: "ƒ goForward() {}",
    block: "ƒ block() {}",
    listen: "ƒ listen() {}"
  },
  user: {
    user: null,
    status: null,
    error: null,
    loading: false,
    message: null,
    isLoggedIn: false,
    globalAccessTokenStatus: null,
    customerAccessTokenStatus: null,
    loginUserStatus: null,
    refreshCustomerAccessTokenStatus: null
  },
  loginFromMyBag: false,
  activeNonEligibleCouponList: [],
  activeEligibleCouponList: []
};

export const productCouponDetailsActiveInactive = {
  closeModal: () => {},
  applyUserCoupon: () => {},
  releaseUserCoupon: () => {},
  type: "mplFinalVisibleCouponsDTO",
  status: "Success",
  activeEligibleCouponList: [
    '{couponCode: "AXIS5_Coupon", couponCreationDate: "M…}',
    '{couponCode: "AXIS10_Coupon", couponCreationDate: "…}'
  ],
  activeNonEligibleCouponList: [
    '{couponCode: "CLIQLATV500", couponCreationDate: "Mo…}',
    '{couponCode: "WATCHAUG", couponCreationDate: "Fri J…}'
  ],
  match: {
    path: "/cart",
    url: "/cart",
    isExact: true,
    params: "{}"
  },
  location: {
    pathname: "/cart",
    search: "",
    hash: "",
    key: "7wlr5w"
  },
  history: {
    length: 8,
    action: "POP",
    location: '{hash: "", key: "7wlr5w", pathname: "/cart", search…}',
    createHref: "ƒ createHref() {}",
    push: "ƒ push() {}",
    replace: "ƒ replace() {}",
    go: "ƒ go() {}",
    goBack: "ƒ goBack() {}",
    goForward: "ƒ goForward() {}",
    block: "ƒ block() {}",
    listen: "ƒ listen() {}"
  },
  cart: {
    status: null,
    error: null,
    loading: false,
    type: null,
    cartIdForLoggedInUserStatus: null,
    cartIdForAnonymousUserStatus: null,
    mergeCartIdStatus: null,
    getUserAddressStatus: "success",
    getUserAddressError: null,
    userCart: null,
    userCartStatus: null,
    userCartError: null,
    cartDetails: '{cartAmount: {…}, cartGuid: "15481123719086096-1865…}',
    cartDetailsStatus: "success",
    cartDetailsError: null,
    loadingForCartDetail: false,
    cartDetailsCNC: null,
    cartDetailsCNCStatus: null,
    cartDetailsCNCError: null,
    cartDetailsCNCLoader: false,
    eddDetails: null,
    eddDetailsStatus: null,
    eddDetailsError: null,
    loadingForEddDetails: false,
    couponStatus: "success",
    couponError: null,
    coupons: "{activeEligibleCouponList: Array(5), activeNonEligi…}",
    loadingForDisplayCoupon: false,
    deliveryModes: null,
    userAddress: '{addresses: Array(1), status: "Success"}',
    setAddress: null,
    netBankDetailsStatus: null,
    netBankDetailsError: null,
    netBankDetails: null,
    emiBankDetails: null,
    emiBankStatus: null,
    orderSummary: null,
    orderSummaryStatus: null,
    orderSummaryError: null,
    storeDetails: "[]",
    storeStatus: null,
    storeError: null,
    storeAdded: null,
    softReserve: null,
    softReserveStatus: null,
    softReserveError: null,
    createPaymentOrder: null,
    createPaymentOrderStatus: null,
    createPaymentOrderError: null,
    collectPaymentOrder: null,
    collectPaymentOrderStatus: null,
    collectPaymentOrderError: null,
    getPrepaidOrderPaymentConfirmation: null,
    getPrepaidOrderPaymentConfirmationStatus: null,
    getPrepaidOrderPaymentConfirmationError: null,
    paymentModes: null,
    paymentModesStatus: null,
    paymentModesError: null,
    bankOffer: null,
    bankOfferStatus: null,
    bankOfferError: null,
    cliqCashPaymentStatus: null,
    cliqCashPaymentStatusError: null,
    cliqCashPaymentDetails: null,
    jusPayStatus: null,
    jusPayError: null,
    jusPayDetails: null,
    cliqCashJusPayDetails: null,
    cliqCashStripeDetails: null,
    createJusPayStatus: null,
    createJusPayError: null,
    transactionDetailsStatus: null,
    transactionDetailsError: null,
    transactionDetailsDetails: null,
    orderConfirmationDetailsStatus: null,
    orderConfirmationDetailsError: null,
    orderConfirmationDetails: null,
    justPayPaymentDetailsStatus: null,
    justPayPaymentDetailsError: null,
    justPayPaymentDetails: null,
    codEligibilityStatus: null,
    codEligibilityError: null,
    codEligibilityDetails: null,
    binValidationCODStatus: null,
    binValidationCODError: null,
    binValidationCODDetails: null,
    transactionCODStatus: null,
    transactionCODError: null,
    softReserveCODPaymentStatus: null,
    softReserveCODPayment: null,
    softReserveCODPaymentError: null,
    orderExperienceStatus: null,
    orderExperience: null,
    orderExperienceError: null,
    binValidationStatus: null,
    bankGatewayStatus: null,
    binValidationError: null,
    binValidationDetails: null,
    removeCartItemStatus: null,
    removeCartItemError: null,
    removeCartItemLoggedOutStatus: null,
    removeCartItemLoggedOutError: null,
    updateQuantityLoggedInStatus: null,
    updateQuantityLoggedInDetails: null,
    updateQuantityLoggedInError: null,
    updateQuantityLoggedOutStatus: null,
    updateQuantityLoggedOutDetails: null,
    updateQuantityLoggedOutError: null,
    AddUserAddressStatus: null,
    AddUserAddressError: null,
    addingAddress: false,
    returnCliqPiqStatus: null,
    returnCliqPiqDetails: null,
    returnCliqPiqError: null,
    softReservationForPaymentStatus: null,
    softReservationForPaymentError: null,
    softReservationForPaymentDetails: null,
    jusPayTokenizeStatus: null,
    jusPayTokenizeError: null,
    jusPayTokenizeDetails: null,
    stripeTokenizeStatus: null,
    stripeTokenizeError: null,
    stripeTokenizeDetails: null,
    createJusPayOrderStatus: null,
    createJusPayOrderError: null,
    createJusPayOrderDetails: null,
    jusPaymentLoader: false,
    stripePaymentLoader: false,
    selectDeliveryModeLoader: false,
    transactionStatus: null,
    loginFromMyBag: false,
    emiEligibilityStatus: null,
    emiEligibilityDetails: null,
    emiEligibilityError: null,
    bankAndTenureStatus: null,
    bankAndTenureDetails: null,
    bankAndTenureError: null,
    emiTermsAndConditionStatus: null,
    emiTermsAndConditionDetails: null,
    emiTermsAndConditionError: null,
    noCostEmiStatus: null,
    noCostEmiDetails: null,
    noCostEmiError: null,
    emiItemBreakUpStatus: null,
    emiItemBreakUpDetails: null,
    emiItemBreakUpError: null,
    paymentFailureOrderDetailsStatus: null,
    paymentFailureOrderDetailsError: null,
    paymentFailureOrderDetails: null,
    isCreatePaymentOrderFailed: false,
    isCollectPaymentOrderFailed: false,
    isGetPrepaidOrderPaymentConfirmationFailed: false,
    isSoftReservationFailed: false,
    isPaymentProceeded: false,
    bankOfferTncDetails: null,
    bankOfferTncStatus: null,
    bankOfferTncError: null,
    loadingForBankOfferTNC: false,
    tempCartIdForLoggedInUserStatus: null,
    tempCartIdForLoggedInUser: null,
    tempCartIdForLoggedInUserError: null,
    tempCartIdForLoggedInUserLoading: null,
    mergeTempCartWithOldCartStatus: null,
    mergeTempCartWithOldCart: null,
    mergeTempCartWithOldCartError: null,
    mergeTempCartWithOldCartLoading: null,
    resetAllPaymentModeFlag: false,
    feedBackDetails: null,
    feedBackDetailsStatus: null,
    feedBackDetailsError: null,
    loadingForfeedBackDetails: false,
    feedBackSent: null,
    feedBackSentStatus: null,
    feedBackSentError: null,
    loadingForfeedBackSent: false,
    getUserAddressAndDeliveryModesByRetryPaymentStatus: null,
    getUserAddressAndDeliveryModesByRetryPayment: null,
    loadingForGetUserAddressAndDeliveryModesByRetryPayment: false,
    getUserAddressAndDeliveryModesByRetryPaymentError: null,
    binValidationOfEmiEligibleStatus: null,
    binValidationOfEmiEligible: null,
    loadingForBinValidationOfEmiEligible: false,
    binValidationOfEmiEligibleError: null,
    cartCountStatus: "success",
    cartCountError: null,
    cartCount: "2",
    cartCountDetails: '{code: "15481123719086096-186598462", count: "2", g…}',
    cartCountDetailsLoading: false,
    minicartStatus: null,
    minicartError: null,
    minicart: null,
    orderConfirmationBannerDetailsStatus: null,
    orderConfirmationBannerDetails: null,
    orderConfirmationBannerDetailsLoading: false,
    orderConfirmationBannerDetailsError: null,
    removeExchangeStatus: null,
    removeExchangeLoading: false,
    removeExchangeDetails: null,
    removeExchangeError: null,
    upiMiddleLayerIsNewStatus: null,
    upiMiddleLayerIsNew: null,
    upiMiddleLayerIsNewLoading: false,
    upiMiddleLayerIsNewError: null,
    instacredMiddleLayerISEnableStatus: null,
    instacredMiddleLayerISEnable: null,
    instacredMiddleLayerISEnableLoading: false,
    instacredMiddleLayerISEnableError: null,
    upiMiddleLayerHowItWorksStatus: null,
    upiMiddleLayerHowItWorks: null,
    upiMiddleLayerHowItWorksLoading: false,
    upiMiddleLayerHowItWorksError: null,
    upiMiddleLayerCombinedLogoStatus: null,
    upiMiddleLayerCombinedLogo: null,
    upiMiddleLayerCombinedLogoLoading: false,
    upiMiddleLayerCombinedLogoError: null,
    feedBackPageStatus: null,
    feedBackPageData: null,
    loadingForfeedBackPage: false,
    feedBackPageError: null,
    getCustomComponent: null,
    getCustomComponentError: null,
    getCustomComponentLoading: false,
    emiEligibiltyDetails: null,
    emiEligibiltyStatus: null,
    emiEligibiltyError: null,
    dCEmiBankDetails: null,
    dCEmiBankDetailsStatus: null,
    dCEmiBankDetailsError: null
  },
  user: {
    user: null,
    status: null,
    error: null,
    loading: false,
    message: null,
    isLoggedIn: false,
    globalAccessTokenStatus: null,
    customerAccessTokenStatus: null,
    loginUserStatus: null,
    refreshCustomerAccessTokenStatus: null
  },
  loginFromMyBag: false,
  loadingForCartDetail: false,
  wishListCount: 0,
  displayToast: () => {},
  showAuthPopUp: () => {},
  getUserAddress: () => {},
  opencouponsList: []
};

export const couponDetailsMock = {
  promotionTitle: "AXIS5_Coupon",
  dateTime: "Sun Apr 11 06:06:06 IST 2021",
  amount: 500,
  couponType: "COUPON",
  value: "AXIS5_Coupon",
  selected: false,
  selectItem: "ƒ selectItem() {}"
};
