export const IMAGE_GALLERY_COMPONENT = "imageGalleryComponent";
export const PRODUCT_AND_BRAND_COMPONENT = "productAndBrandComponent";
export const RATING_REVIEW_COMPONENT = "ratingReviewShortComponent";
export const PRICE_COMPONENT = "priceComponent";
export const SIZE_COMPONENT = "sizeComponent";
export const COLOR_COMPONENT = "colorComponent";
export const FREEBIE_COMPONENT = "freebeeComponent";
export const OFFERS_COMPONENT = "offersComponent";
export const STORY_COMPONENT = "storyComponent";
export const DETAILS_COMPONENT = "detailsShortComponent";
export const FROM_THE_BRAND_COMPONENT = "fromTheBrandComponent";
export const INGREDIENTS_COMPONENT = "ingredientsComponent";
export const HOW_TO_WEAR_COMPONENT = "howToWearComponent";
export const SHIPPING_DETAIL_COMPONENT = "shippingDetailComponent";
export const GUARANTEE_COMPONENT = "guaranteeComponent";
export const RATING_REVIEW_DETAIL_COMPONENT = "ratingReviewDetailComponent";
export const EXPERT_TALK_COMPONENT = "expertTalkComponent";
export const RETURNS_COMPONENT = "returnsComponent";
export const ABOUT_THE_BRAND_COMPONENT = "aboutTheBrandComponent";
export const USE_IT_TOGETHER_COMPONENT = "useItTogetherComponent";
export const MORE_FROM_THIS_BRAND_COMPONENT = "moreFromThisBrandComponent";
export const SIMILAR_BRANDS_COMPONENT = "similarBrandsComponent";
export const LISTING_ID_COMPONENT = "listingIdComponent";
export const BUYNOW_ADDTOBAG_COMPONENT = "buyNowAddToBagComponent";
export const PRODUCT_BADGES_COMPONENT = "productBadgeComponent";

export const BUYNOW = "buyNow";
export const ADDTOBAG = "addToBag";
export const WISHLIST = "wishList";
export const CERTIFIED_COMPONENT = "certifiedComponent";

export const SECTION_OF_ALL_BEAUTY_COMPONENTS = [
  IMAGE_GALLERY_COMPONENT,
  PRODUCT_AND_BRAND_COMPONENT,
  RATING_REVIEW_COMPONENT,
  RATING_REVIEW_DETAIL_COMPONENT,
  PRICE_COMPONENT,
  SIZE_COMPONENT,
  OFFERS_COMPONENT,
  SHIPPING_DETAIL_COMPONENT,
  COLOR_COMPONENT,
  GUARANTEE_COMPONENT,
  FREEBIE_COMPONENT,
  DETAILS_COMPONENT,
  INGREDIENTS_COMPONENT,
  HOW_TO_WEAR_COMPONENT,
  STORY_COMPONENT,
  FROM_THE_BRAND_COMPONENT,
  MORE_FROM_THIS_BRAND_COMPONENT,
  RETURNS_COMPONENT,
  ABOUT_THE_BRAND_COMPONENT,
  SIMILAR_BRANDS_COMPONENT,
  BUYNOW_ADDTOBAG_COMPONENT,
  CERTIFIED_COMPONENT,
  PRODUCT_BADGES_COMPONENT
];

export const SECTION_OF_PRODUCT_DETAILS = [
  PRODUCT_AND_BRAND_COMPONENT,
  RATING_REVIEW_COMPONENT,
  PRICE_COMPONENT,
  SIZE_COMPONENT,
  OFFERS_COMPONENT,
  SHIPPING_DETAIL_COMPONENT,
  COLOR_COMPONENT,
  GUARANTEE_COMPONENT,
  FREEBIE_COMPONENT,
  DETAILS_COMPONENT,
  BUYNOW_ADDTOBAG_COMPONENT,
  CERTIFIED_COMPONENT
];

export const SECTION_OF_PRODUCT_DESCRIPTION = [
  INGREDIENTS_COMPONENT,
  HOW_TO_WEAR_COMPONENT,
  STORY_COMPONENT,
  DETAILS_COMPONENT,
  FROM_THE_BRAND_COMPONENT,
  MORE_FROM_THIS_BRAND_COMPONENT,
  RETURNS_COMPONENT,
  ABOUT_THE_BRAND_COMPONENT,
  SIMILAR_BRANDS_COMPONENT,
  RATING_REVIEW_DETAIL_COMPONENT
];
